% CIA.M : sets parameters and simulates cash-in-advance model !
% 
% SET THE BASELINE PARAMETERS HERE
%
% for help, see Section 3.4 of my BC EC861 lecture notes 2002-3

clear;
close all;


r_a = .95 ; % TECHNOLOGY SHOCK PERSISTENCE
r_u = .8; % money shock persistence
corr_a_u = 0; % CORRELATION B/W SHOCKS

sd_a = 0.03 ;
sd_u = 0.0089 ;

a = .36; % SHARE OF K IN PROD FUNCTION
d = .019 ; % DEPRECIATION RATE OF CAPITAL
be = .989; % beta
pi = 1.0125; % STEADY STATE INFLATION RATE
fi = 2;     % CONSUMPTION ELASTICITY OF SUBSTITUTION
eta = 1.5; % PARAMETER DESCRIBING HOW ELASTIC LABOUR SUPPLY IS  [ LAB_ELASTICITY IS 1/(ETA-1) ]
           


% A BUNCH OF OPTIONS THAT YOU DONT WANT TO CHANGE HERE
axistight=1; grids=1;


% HERE YOU HAVE THE CHANCE TO CALIBRATE A FEW PARAMETERS AND THEN COMPARE THE IMPULSE RESPONSES OF THE MODEL
% CHANGING SOME OF THEM EACH TIME

% FIRST CALIBRATION. 

cha=0; % CHA=0 MEANS THAT THE IRF WILL BE RED/CIRCLED
CIA_go % RUNS THE MODEL, DONT CHANGE 

% 
% % SECOND CALIBRATION
cha=1; % CHA=1 MEANS THAT THE IRF WILL BE BLUE/TRIANGLES
r_u=0.5; 
CIA_go % RUNS THE MODEL, DONT CHANGE 


