% WORK ON THIS AND PLAY WITH THE SIDRAUSKI MDOEL!!!!
% SET THE BASELINE PARAMETERS HERE

clear;
close all;


r_a = .95 ; % TECHNOLOGY SHOCK PERSISTENCE
r_u = .95 ; % money shock persistence
corr_a_u = 0; % CORRELATION B/W SHOCKS

sd_a = 0.03 ;
sd_u = 0.0089 ;

a = .4; % SHARE OF K IN PROD FUNCTION
d = .019 ; % DEPRECIATION RATE OF CAPITAL
be = .99; % beta
b = .005; % WEIGHT ON REAL BALANCES IN MOMENTARY UTILITY FUNCTIONS
pi = 1.0125; % STEADY STATE INFLATION RATE
fi = 1; % SUBSTITUTABILITY BETWEEN C AND M/P
eta = 1.005; % PARAMETER DESCRIBING HOW ELASTIC LABOUR SUPPLY IS  [ LAB_ELASTICITY IS 1/(ETA-1) ]


% A BUNCH OF OPTIONS THAT YOU DONT WANT TO CHANGE HERE
axistight=1; grids=1;


% HERE YOU HAVE THE CHANCE TO CALIBRATE A FEW PARAMETERS AND THEN COMPARE THE IMPULSE RESPONSES OF THE MODEL
% CHANGING SOME OF THEM EACH TIME

% FIRST CALIBRATION. 
cha=0; % CHA=0 MEANS THAT THE IRF WILL BE RED/CIRCLED
fi=1; eta=1.01; 
sidrauski_go % RUNS THE MODEL, DONT CHANGE 

% SECOND CALIBRATION
cha=1; % CHA=1 MEANS THAT THE IRF WILL BE BLUE/TRIANGLES
fi=4; eta=1.01; 
sidrauski_go % RUNS THE MODEL, DONT CHANGE 

cha=2; % CHA=2 MEANS THAT THE IRF WILL BE BLACK/SQUARES. DONT CHANGE THIS LINE
fi=4; eta=10; 
sidrauski_go % RUNS THE MODEL, DONT CHANGE 

% FOR INSTANCE, HERE WE PLAY WITH THE ELASTICITY OF SUBSTITUTION B/W MONEY AND CONSUMPTION AND 
% WITH THE LABOUR SUPPLY ELASTICITY