
% SIMULATES OPTIMAL POLICY IN GIANNONI AND WOODFORD (2002), OPTIMAL INTEREST RATE RULES
% Giannoni, Marc, and Michael Woodford (2002), "Optimal Interest-Rate Rules: II. Applications," , mimeo
% BASED ON CHAPTER 6 IN THE LECTURE NOTES  

% IF YOU HAVE ANY PROBLEMS EITHER SAY A PRAYER OR ASK YOUR FLATMATES OR EMAIL ME AT IACOVIEL@BC.EDU
% @ MATTEO IACOVIELLO, 2002

% TO BE RUN TOGETHER WITH COMPANION FILE GIANNONI_GO

clear;
close all;


% system is described by:


b = .99; % DISCOUNT RATE
s = .157; % ELASTICITY OF SUBSTITUTION in consumption

lx = .047; % WEIGHT ON OUTPUT GAP RELATIVE TO INFLATION
lr = .233; % WEIGHT ON INTEREST RATE VOLATILITY RELATIVE TO INFLATION

k = .024;


r_u = 0.5 ; % persistence in inefficient supply shock
r_n = 0.5 ; % persistence in demand (natural rate) shock

sd_n = 0.03 ;
sd_u = 0.02 ;

HORIZON=20; % TIME HORIZON FOR THE IMPULSE RESPONSES



% A BUNCH OF OPTIONS THAT YOU DONT WANT TO CHANGE HERE
axistight=1; grids=1;



% HERE YOU HAVE THE CHANCE TO CALIBRATE A FEW PARAMETERS AND THEN COMPARE THE IMPULSE RESPONSES OF THE MODEL
% CHANGING SOME OF THEM EACH TIME



cha=0; % THIS CHA=0 MEANS THAT IMPULSE RESPONSES WILL BE RED
giannoni_go ;

cha=1; % THIS CHA=1 MEANS THAT IMPULSE RESPONSES WILL BE BLUE
k = .01;
giannoni_go ;

